# Generated by Django 6.0 on 2025-12-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tactic_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('framework', models.CharField(choices=[('attack', 'MITRE ATT&CK'), ('atlas', 'MITRE ATLAS')], max_length=10)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['tactic_id'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('framework', models.CharField(choices=[('attack', 'MITRE ATT&CK'), ('atlas', 'MITRE ATLAS')], max_length=10)),
                ('url', models.URLField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtechniques', to='mitre.technique')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='mitre.tactic')),
            ],
            options={
                'ordering': ['technique_id'],
            },
        ),
    ]
