# Generated by Django 5.2.14 on 2026-06-08 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('attack', 'MITRE ATT&CK'), ('atlas', 'MITRE ATLAS')], max_length=10, unique=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('source', models.URLField(blank=True, max_length=500)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tactic_count', models.PositiveIntegerField(default=0)),
                ('technique_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['framework'],
            },
        ),
    ]
