# Generated by Django 5.2.14 on 2026-05-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('django_group', 'Django Group'), ('external_group', 'External Group'), ('claim', 'Claim')], default='django_group', max_length=30)),
                ('external_value', models.CharField(blank=True, help_text='External group ID or claim value from AD/Entra/OIDC/SAML.', max_length=300)),
                ('claim_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('business_unit_owner', 'Business Unit Owner'), ('security_admin', 'Security Admin')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='organization.businessunit')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
