# Generated by Django 6.0 on 2025-12-16 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mitre', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_id', models.CharField(max_length=50)),
                ('scenario', models.TextField()),
                ('threat_object', models.CharField(max_length=300)),
                ('threat_catalog_rating', models.CharField(blank=True, choices=[('almost_certain', 'Almost Certain'), ('likely', 'Likely'), ('possible', 'Possible'), ('unlikely', 'Unlikely'), ('rare', 'Rare')], max_length=20)),
                ('stride_category', models.CharField(choices=[('S', 'Spoofing'), ('T', 'Tampering'), ('R', 'Repudiation'), ('I', 'Information Disclosure'), ('D', 'Denial of Service'), ('E', 'Elevation of Privilege')], max_length=1)),
                ('inherent_risk', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('residual_risk', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mitigations', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mitre_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='mitre.technique')),
            ],
            options={
                'ordering': ['threat_id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='threatmodels.finding')),
            ],
            options={
                'verbose_name_plural': 'Evidence',
            },
        ),
        migrations.CreateModel(
            name='ThreatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('overall_risk', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threat_models', to='organization.businessunit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_threat_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='threat_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='threatmodels.threatmodel'),
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='diagrams/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='threatmodels.threatmodel')),
            ],
        ),
    ]
