# Generated by Django 5.2.9 on 2025-12-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='threat_models', to='threatmodels.technologytag'),
        ),
    ]
