# Generated by Django 6.0 on 2026-03-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatmodels', '0002_technologytag_threatmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='diagram_type',
            field=models.CharField(choices=[('architecture', 'Architecture Diagram'), ('threat_model', 'Threat Model Diagram'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
