# Generated by Django 5.2.14 on 2026-06-08 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitre', '0002_frameworkimport'),
        ('threatmodels', '0004_finding_acceptance_reason_finding_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='external_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='external_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='source_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('threat_model', 'external_id'), name='unique_finding_external_id_per_threat_model'),
        ),
    ]
